### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by Nord1cWarr1or** [meKryztal/steamify#4]
```
--------------------------------------------------
[2024-09-09 16:17:52] Номер аккаунта: 5
[2024-09-09 16:17:52] Аккаунт: y
[2024-09-09 16:17:52] Общий баланс: 465.0
[2024-09-09 16:17:52] Забрал с фарминга: 60
[2024-09-09 16:17:52] Запустил фарминг
[2024-09-09 16:17:53] Нечего забирать с реферального бонуса
[2024-09-09 16:17:55] Уже делал чекин сегодня
[2024-09-09 16:17:55] Забрал sparks: 0.0
--------------------------------------------------
[2024-09-09 18:23:28] Номер аккаунта: 1
[2024-09-09 18:23:28] Аккаунт: x
[2024-09-09 18:23:29] Общий баланс: 645.0
[2024-09-09 18:23:29] Еще не пришло время клейма
[2024-09-09 18:23:30] Фарминг уже запущен
[2024-09-09 18:23:30] Нечего забирать с реферального бонуса
Traceback (most recent call last):
File "/home/wp/tgbots/steamify/venv/lib/python3.11/site-packages/requests/models.py", line 974, in json
return complexjson.loads(self.text, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/wp/.pyenv/versions/3.11.5/lib/python3.11/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/wp/.pyenv/versions/3.11.5/lib/python3.11/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/wp/.pyenv/versions/3.11.5/lib/python3.11/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/wp/tgbots/steamify/steamify.py", line 333, in <module>
app.main()
File "/home/wp/tgbots/steamify/steamify.py", line 70, in main
self.process_account(new_data)
File "/home/wp/tgbots/steamify/steamify.py", line 80, in process_account
self.solve_task(data)
File "/home/wp/tgbots/steamify/steamify.py", line 234, in solve_task
response_json = res.json()
^^^^^^^^^^
File "/home/wp/tgbots/steamify/venv/lib/python3.11/site-packages/requests/models.py", line 978, in json
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Nord1cWarr1or** [comment]
Исправлено в https://github.com/meKryztal/steamify/commit/2d9198a49916125460137822ca412a514efa8c6d
