### ISSUE TITLE
Ошибка авторизации после обновления

### ISSUE THREAD

**Issue by Nord1cWarr1or** [meKryztal/steamify#5]
```
[2024-09-11 13:38:31] Номер аккаунта: 1
[2024-09-11 13:38:31] Аккаунт: x
[2024-09-11 13:38:31] {"success":false,"msg":"invalid authorization token","data":null,"errors":null}
Traceback (most recent call last):
File "/home/wp/tgbots/steamify/steamify.py", line 358, in <module>
app.main()
File "/home/wp/tgbots/steamify/steamify.py", line 70, in main
self.process_account(new_data)
File "/home/wp/tgbots/steamify/steamify.py", line 76, in process_account
self.get_me(data)
File "/home/wp/tgbots/steamify/steamify.py", line 129, in get_me
balance = response_json.get('data', {}).get('points', 'N/A')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by Nord1cWarr1or** [comment]
Прошу прощения, надо было обновить данные инициализации
